const LOAD = 'LOAD_'
const ADD = 'ADD_'
const SELECT = 'SELECT_'
const REMOVE = 'REMOVE_'
const UPDATE = 'UPDATE_'

export const START = '_START'
export const SUCCESS = '_SUCCESS'
export const FAIL = '_FAIL'

export const LOAD_DICTIONARIES = 'LOAD_DICTIONARIES'

export const LOAD_SECTIONS = 'LOAD_SECTIONS'

export const SET_ENTITY_CODE = 'SET_ENTITY_CODE'

const EVENT = 'EVENT'
export const LOAD_EVENT = LOAD + EVENT
export const SELECT_EVENT = SELECT + EVENT
export const REMOVE_EVENT = REMOVE + EVENT
export const ADD_EVENT = ADD + EVENT

const PROVIDER = 'PROVIDER'
export const LOAD_PROVIDER = LOAD + PROVIDER
export const ADD_PROVIDER = ADD + PROVIDER
export const REMOVE_PROVIDER = REMOVE + PROVIDER
export const UPDATE_PROVIDER_DATA = `${UPDATE + PROVIDER}_DATA`

const RULE = 'RULE'
export const ADD_RULE = ADD + RULE
export const REMOVE_RULE = REMOVE + RULE
export const UPDATE_RULE_TEMPLATE = `${UPDATE + RULE}_TEMPLATE`
export const UPDATE_RULE_LOGIC = `${UPDATE + RULE}_LOGIC`
export const UPDATE_RULE_ASSERTIONS = `${UPDATE + RULE}_ASSERTIONS`
export const UPDATE_RULE_CONSUMER = `${UPDATE + RULE}_CONSUMER`
export const ADD_RULE_CONSUMER = `${ADD_RULE}_CONSUMER`
export const REMOVE_RULE_CONSUMER = `${REMOVE_RULE}_CONSUMER`
